
#! /bin/bash
notedown '00_강의계획서.ipynb' --to markdown --strip > '00_강의계획서.md'
notedown '0101_왜.ipynb' --to markdown --strip > '0101_왜.md'
notedown '0102_새로운 패러다임.ipynb' --to markdown --strip > '0102_새로운 패러다임.md'
notedown '0103_로봇 구조설계자를 위한 강력한 오픈소스 소프트웨어들.ipynb' --to markdown --strip > '0103_로봇 구조설계자를 위한 강력한 오픈소스 소프트웨어들.md'
notedown '0104_실무에 적용하면 이렇게 좋아진다.ipynb' --to markdown --strip > '0104_실무에 적용하면 이렇게 좋아진다.md'
notedown '0105_VirtualBox 가상머신에 CubLinux 설치하기.ipynb' --to markdown --strip > '0105_VirtualBox 가상머신에 CubLinux 설치하기.md'
notedown '0106_VirtualBox 가상머신에 CubLinux 설치하기.ipynb' --to markdown --strip > '0106_VirtualBox 가상머신에 CubLinux 설치하기.md'
notedown '0107_시스템 환경 구성하면서 Linux 사용방법 익히기.ipynb' --to markdown --strip > '0107_시스템 환경 구성하면서 Linux 사용방법 익히기.md'
notedown '0108_시스템 환경 구성하면서 Linux 사용방법 익히기.ipynb' --to markdown --strip > '0108_시스템 환경 구성하면서 Linux 사용방법 익히기.md'
notedown '0201_스크립트 프로그래밍 환경을 구축하고 실제로 써보자.ipynb' --to markdown --strip > '0201_스크립트 프로그래밍 환경을 구축하고 실제로 써보자.md'
notedown '0202_Scilab, GNU Octave, Scientific Python, Julia를 설치해서 간단히 사용해 보기.ipynb' --to markdown --strip > '0202_Scilab, GNU Octave, Scientific Python, Julia를 설치해서 간단히 사용해 보기.md'
notedown '0203_Jupyter를 설치해서 간단히 사용해 보기.ipynb' --to markdown --strip > '0203_Jupyter를 설치해서 간단히 사용해 보기.md'
notedown '0204_Light Table 에디터 설치해서 간단히 사용해 보기.ipynb' --to markdown --strip > '0204_Light Table 에디터 설치해서 간단히 사용해 보기.md'
notedown '0205_Git 소개,설치 및 Github 계정 만들고 연계시키기.ipynb' --to markdown --strip > '0205_Git 소개,설치 및 Github 계정 만들고 연계시키기.md'
notedown '0206_Extensions 설치 후 Jupyter와 연계해 보기.ipynb' --to markdown --strip > '0206_Extensions 설치 후 Jupyter와 연계해 보기.md'
notedown '0207_ 모바일 로봇의 완충 장치 설계.ipynb' --to markdown --strip > '0207_ 모바일 로봇의 완충 장치 설계.md'
notedown '0208_모바일 로봇의 구동용 감속기 사양 결정.ipynb' --to markdown --strip > '0208_모바일 로봇의 구동용 감속기 사양 결정.md'
notedown '0301_오픈소스 유한요소해석 소프트웨어들의 활용 개념.ipynb' --to markdown --strip > '0301_오픈소스 유한요소해석 소프트웨어들의 활용 개념.md'
notedown '0302_FreeCAD, Elmer, Z88 소개 및 설치하기.ipynb' --to markdown --strip > '0302_FreeCAD, Elmer, Z88 소개 및 설치하기.md'
notedown '0303_GMSH, Paraview, DraftSight 소개 및 설치하기.ipynb' --to markdown --strip > '0303_GMSH, Paraview, DraftSight 소개 및 설치하기.md'
notedown '0304_Salome Meca, OpenFOAM 소개 및 설치하기.ipynb' --to markdown --strip > '0304_Salome Meca, OpenFOAM 소개 및 설치하기.md'
notedown '0305_FreeCAD로 부품 모델링하고 간단하게 구조해석 해 보기.ipynb' --to markdown --strip > '0305_FreeCAD로 부품 모델링하고 간단하게 구조해석 해 보기.md'
notedown '0306_Z88 Aurora, ElmerFEM으로 구조해석 하고 Paraview로 결과 만들어 보기.ipynb' --to markdown --strip > '0306_Z88 Aurora, ElmerFEM으로 구조해석 하고 Paraview로 결과 만들어 보기.md'
notedown '0307_GMSH, Salome 사용해 보기.ipynb' --to markdown --strip > '0307_GMSH, Salome 사용해 보기.md'
notedown '0308_GMSH, ElmerFEM으로 유체동역학 및 멀티피직스 해석해 보기.ipynb' --to markdown --strip > '0308_GMSH, ElmerFEM으로 유체동역학 및 멀티피직스 해석해 보기.md'
notedown '0409_부록.ipynb' --to markdown --strip > '0409_부록.md'
